<?xml version="1.0" encoding="utf-8"?><Database Name="Shikhai" Class="ShikhaiDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost\sqlexpress;Initial Catalog=Shikhai;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DefaultConnection" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BannerImageTbl" Member="BannerImageTbls">
    <Type Name="BannerImageTbl">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="URL" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ImagePath" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MerchantId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CategoryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BannerGuidId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UserTbl" Member="UserTbls">
    <Type Name="UserTbl">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="NoOfVisits" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastLoginDateUtc" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="LastLoginIP" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="FailedLoginAttempts" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CannotLoginUntilDateUtc" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="CreatedOnUtc" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="UpdatedOnUtc" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BannerTbl" Member="BannerTbls">
    <Type Name="BannerTbl">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CreatedOnUtc" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="UpdatedOnUtc" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Published" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GuidId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="IsHomePageBanner" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CategoryTbl" Member="CategoryTbls">
    <Type Name="CategoryTbl">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name_English" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Name_Bangla" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImagePath" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Parent1Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShowOnHomePage" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IncludeInTopMenu" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedOnUtc" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="UpdatedOnUtc" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Published" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ClassNameTbl" Member="ClassNameTbls">
    <Type Name="ClassNameTbl">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedOnUtc" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="UpdatedOnUtc" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Published" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CustomerSearchTbl" Member="CustomerSearchTbls">
    <Type Name="CustomerSearchTbl">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Keyword" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="IpAddress" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CreatedOnUtc" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GeoZoneTbl" Member="GeoZoneTbls">
    <Type Name="GeoZoneTbl">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DateAdded" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateModified" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LocationTbl" Member="LocationTbls">
    <Type Name="LocationTbl">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedOnUtc" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="UpdatedOnUtc" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Published" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LogTbl" Member="LogTbls">
    <Type Name="LogTbl">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ExceptionMessage" Type="System.String" DbType="NVarChar(3050)" CanBeNull="true" />
      <Column Name="ExceptionStackTrace" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ControllerName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="IpAddress" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Browser" Type="System.String" DbType="NVarChar(3050)" CanBeNull="true" />
      <Column Name="OS" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ActionName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CreatedOnUtc" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NewspaperTbl" Member="NewspaperTbls">
    <Type Name="NewspaperTbl">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NewsGuidId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="NewspaperName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AdLocation" Type="System.String" DbType="NVarChar(127)" CanBeNull="true" />
      <Column Name="PriceDescription" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdvertiserName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AdvertiserAddress" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AdvertiserMobile" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="AdvertiserEmail" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DateofPublication" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="ColumnSize" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Inch" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalColumnInch" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalPrice" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdCategoryId" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MainImagePath" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedOnUtc" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="UpdatedOnUtc" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderPaymentMethodTbl" Member="OrderPaymentMethodTbls">
    <Type Name="OrderPaymentMethodTbl">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Instructions" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="InstructionsImageUrl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Published" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderPaymentStatusTbl" Member="OrderPaymentStatusTbls">
    <Type Name="OrderPaymentStatusTbl">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DefaultStatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PaymentTbl" Member="PaymentTbls">
    <Type Name="PaymentTbl">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PaymentGuidId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CreatedOnUtc" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="UpdatedOnUtc" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="OrderId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PaymentChannel" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PaymentMobile" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="PaymentTrxId" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="PaymentAmount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductTbl" Member="ProductTbls">
    <Type Name="ProductTbl">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsBook" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsStationary" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="InstructionsImageUrl" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Published" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ShowOnHomePage" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedOnUtc" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="UpdatedOnUtc" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RangeTbl" Member="RangeTbls">
    <Type Name="RangeTbl">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LowerLimit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UpperLimit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedOnUtc" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="UpdatedOnUtc" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Published" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TeacherTbl" Member="TeacherTbls">
    <Type Name="TeacherTbl">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GuidId" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="RegistrationNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RegistrationType" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="ClinicHospitalName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Designation" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="YearOfExperience" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="WorkingArea" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Addresss" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CanVisitDays" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CanTeachClass" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="SelectedLocationId" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="SelectedCategory" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CanTeachSubject" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="TutionPrice" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VisitTimeStart" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="VisitTimeEnd" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="SlotDuration" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VisitingCard" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="CreatedOnUtc" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="UpdatedOnUtc" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TestimonialTbl" Member="TestimonialTbls">
    <Type Name="TestimonialTbl">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ImagePath" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="PersonName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PersonTitle" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedOnUtc" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="UpdatedOnUtc" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Published" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>